(library (emul helper export)
         (export export)
         (import (rnrs)
                 (prefix (emul heap type booleans) target-) 
                 (prefix (emul heap type characters) target-) 
                 (prefix (emul heap type fixnums) target-) 
                 (prefix (emul heap type pairs) target-) 
                 (prefix (emul heap type strings) target-) 
                 (prefix (emul heap type vectors) target-) ))
